stages:
    - linting
    - test

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
      - python -m pip install --upgrade pip
      - pip install flake8
      - pip install flake8-quotes
      - pip install flake8-import-order
      - pip install pep8-naming
      - flake8 --verbose
      - flake8 --inline-quotes '"'.

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
      - python -m pip install --upgrade pip
      - pip install black
      - black --check --verbose --line-length 79 .

test:
  stage: test
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.prod.txt
    - pip install -r requirements.test.txt
    - cd lyceum
    - python manage.py test
