# Generated by Django 4.2.6 on 2023-10-21 11:23

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'name',
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name='Название',
                    ),
                ),
                (
                    'slug',
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                            django.core.validators.RegexValidator(
                                re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                'invalid',
                            ),
                        ],
                        verbose_name='Слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='Вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'name',
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name='Название',
                    ),
                ),
                (
                    'slug',
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                            django.core.validators.RegexValidator(
                                re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                'invalid',
                            ),
                        ],
                        verbose_name='Слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                ('name', models.TextField(help_text='max 150 символов')),
                (
                    'text',
                    models.TextField(
                        default='роскошно и превосходно',
                        help_text="Описание должно состояить из более чем 1 слова и содержать слова 'роскошно' или 'превосходно'",
                        validators=[
                            catalog.models.check_two_more_words_validator,
                            catalog.models.excellent_or_luxurious_validator,
                        ],
                        verbose_name='Описание',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='catalog.category',
                    ),
                ),
                ('tags', models.ManyToManyField(to='catalog.tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
